// Generated by CoffeeScript 1.10.0
var app, bodyParser, encryptor, express, fs, multer, secret_key, upload;

express = require('express');

bodyParser = require('body-parser');

multer = require('multer');

fs = require('fs');

upload = multer({
  dest: 'public/uploads/'
});

secret_key = 'this is a really really secret key, oooohhhhhh';

encryptor = require('simple-encryptor')(secret_key);

app = express();

app.use(express["static"](__dirname + '/public'));

app.set('view engine', 'pug');

app.use(bodyParser.urlencoded({
  extended: true
}));

app.use(bodyParser.json());

app.get('/', function(req, res) {
  return res.render('index.pug');
});

app.post('/step-one', function(req, res) {
  return res.send(encryptor.encrypt(req.body));
});

app.post('/step-three', function(req, res) {
  console.log(req.body);
  return res.send(encryptor.encrypt(req.body));
});

app.post('/step-four', function(req, res) {
  console.log(req.body);
  return res.send(encryptor.encrypt(req.body));
});

app.post('/upload-image', upload.single("file"), function(req, res) {
  return res.send(String(req.file.path.replace('public/', '')));
});

app.get('/remove-image/:id', function(req, res) {
  return fs.unlink('public/uploads/' + req.params.id, function(err) {
    if (err) {
      res.send(err);
    }
    return res.send('File deleted successfully!');
  });
});

app.post('/summary-data', function(req, res) {
  var new_summary_data, summary_data;
  summary_data = req.body;
  new_summary_data = {};
  new_summary_data.stepOne = encryptor.decrypt(summary_data['stepOne']);
  new_summary_data.stepTwo = summary_data['stepTwo'];
  new_summary_data.stepThree = encryptor.decrypt(summary_data['stepThree']);
  new_summary_data.stepFour = encryptor.decrypt(summary_data['stepFour']);
  console.log(new_summary_data);
  return res.send(new_summary_data);
});

app.listen(3000);

console.log("Express server listening on port 3000");
