// Generated by CoffeeScript 1.10.0

/* 
StepFour of Sample Workflow
 Requirements:
 	Payment Information
	 	Credit Card Number
	 	Expiration Date
	 	CVC
	 	Name
 */
var ErrorAlert, Input, PaymentForm, React, ReactDOM, StepFour, Submit, a, div, form, getData, getValues, h3, input, label, p, ref;

React = require('react');

ReactDOM = require('react-dom');

ref = React.DOM, div = ref.div, h3 = ref.h3, p = ref.p, form = ref.form, input = ref.input, label = ref.label, a = ref.a;

Input = require('../global/input.js');

getData = require('../functions/get-data.js');

getValues = require('../functions/form-values.js');

Submit = require('../functions/submit.js').StepFour;

ErrorAlert = React.createClass({
  render: function() {
    return div({
      className: 'alert alert-danger text-input-alert',
      role: 'alert'
    }, p({
      className: 'text-input-alert-text'
    }, "Please enter a " + this.props.text));
  }
});

PaymentForm = React.createClass({
  render: function() {
    return div({
      className: 'container'
    }, form, div({
      className: 'form-group billing-form-container',
      id: 'billing-form-container'
    }, React.createElement(Input, {
      id: 'credit-card',
      text: 'Card Number'
    }), this.props.error === 'credit-card' ? React.createElement(ErrorAlert, {
      text: 'Credit Card Number'
    }) : void 0, React.createElement(Input, {
      id: 'exp-date',
      text: 'Expiration Date'
    }), this.props.error === 'exp-date' ? React.createElement(ErrorAlert, {
      text: 'Expiration Date'
    }) : void 0, React.createElement(Input, {
      id: 'cvc',
      text: 'CVC'
    }), this.props.error === 'cvc' ? React.createElement(ErrorAlert, {
      text: 'CVC Number'
    }) : void 0, React.createElement(Input, {
      id: 'card-name',
      text: 'Name on Card'
    }), this.props.error === 'card-name' ? React.createElement(ErrorAlert, {
      text: 'Card Name'
    }) : void 0));
  }
});

StepFour = React.createClass({
  getInitialState: function() {
    return {
      error: false
    };
  },
  handleSubmit: function() {
    var _this, keys;
    console.log('submitting payment info');
    keys = ['credit-card', 'exp-date', 'cvc', 'card-name'];
    _this = this;
    return getValues(keys).then((function(resp) {
      return Submit(resp).then(function(rsp) {
        _this.props.updateData(rsp, 4);
        return _this.props.changeStep(5);
      });
    }), function(err) {
      console.log(err);
      return this.setState({
        error: err
      });
    });
  },
  handleBack: function() {
    return this.props.changeStep(3);
  },
  render: function() {
    return div({
      className: 'container',
      id: 'step-four-container'
    }, div({
      className: 'row'
    }, div({
      className: 'col-sm-2'
    }, a({
      className: 'btn btn-primary',
      onClick: this.handleBack
    }, 'Back')), div({
      className: 'col-sm-8'
    }, h3({}, "Billing Information"), p({}, "Please enter your billing info below")), div({
      className: 'col-sm-2'
    })), React.createElement(PaymentForm, {
      error: this.state.error,
      data: this.props.data
    }), a({
      className: 'btn btn-primary',
      onClick: this.handleSubmit
    }, 'Submit Payment Information'));
  }
});

module.exports = StepFour;
