// Generated by CoffeeScript 1.10.0
var $, getData;

$ = require('jquery');

getData = function(data) {
  var route;
  route = '/get-data/';
  return $.ajax({
    type: 'POST',
    contentType: 'application/json',
    url: route,
    data: JSON.stringify({
      key: data
    }),
    dataType: 'json',
    success: function(response) {
      return response;
    },
    error: function(error) {
      return error;
    }
  });
};

module.exports = getData;
