// Generated by CoffeeScript 1.10.0
var $, RemoveImage;

$ = require('jquery');

RemoveImage = function(img) {
  return new Promise(function(resolve, reject) {
    var route;
    route = '/remove-image/' + img.replace('uploads/', '');
    return $.get(route, function(data) {
      return resolve(data);
    });
  });
};

module.exports = RemoveImage;
