// Generated by CoffeeScript 1.10.0
var $, exports;

$ = require('jquery');

exports = module.exports = {};

exports.StepOne = function(data) {
  var route;
  route = '/step-one';
  return $.ajax({
    type: 'POST',
    contentType: 'application/json',
    url: route,
    data: JSON.stringify(data),
    dataType: 'text',
    success: function(response) {
      return response;
    },
    error: function(error) {
      return error;
    }
  });
};

exports.StepThree = function(data) {
  var route;
  route = '/step-three';
  return $.ajax({
    type: 'POST',
    contentType: 'application/json',
    url: route,
    data: JSON.stringify(data),
    dataType: 'text',
    success: function(response) {
      return response;
    },
    error: function(error) {
      return error;
    }
  });
};

exports.StepFour = function(data) {
  var route;
  route = '/step-four';
  return $.ajax({
    type: 'POST',
    contentType: 'application/json',
    url: route,
    data: JSON.stringify(data),
    dataType: 'text',
    success: function(response) {
      return response;
    },
    error: function(error) {
      return error;
    }
  });
};
