// Generated by CoffeeScript 1.10.0
var $, UploadImage, ajax;

$ = require('jquery');

ajax = function(formData) {
  return $.ajax({
    url: '/upload-image',
    type: 'POST',
    success: function(rsp) {
      return rsp;
    },
    error: function() {
      return 'Something went wrong!';
    },
    data: formData,
    cache: false,
    contentType: false,
    processData: false
  }, 'text');
};

UploadImage = function() {
  return new Promise(function(resolve, reject) {
    var comp, file, formData, name, size, type;
    comp = $('#image-input');
    file = comp[0].files[0];
    name = file.name;
    size = file.size;
    type = file.type;
    if (file.name.length < 1) {
      return reject('no file name');
    } else if (file.size > 100000) {
      return reject('file size is too big');
    } else if (file.type !== 'image/png' && file.type !== 'image/jpg' && file.type !== 'image/gif' && file.type !== 'image/jpeg') {
      return reject('not an image');
    } else {
      formData = new FormData();
      formData.append('file', file);
      return ajax(formData).done(function(m) {
        return resolve(m);
      });
    }
  });
};

module.exports = UploadImage;
