// Generated by CoffeeScript 1.10.0

/* 
StepFour of Sample Workflow
 Requirements:
 	Confirmation
 	Once the entire form is submitted to the server render a confirmation page which shows all the info submitted on prior pages
 	The page should be formatted as an order form, with each uploaded creative appearing as a line item.
 	The state should be retrieved from the server even though this is a single page react app which will have most of the state locally
 */
var GetSummaryData, React, ReactDOM, Summary, SummaryData, a, div, form, h3, input, label, p, ref;

React = require('react');

ReactDOM = require('react-dom');

ref = React.DOM, div = ref.div, h3 = ref.h3, p = ref.p, form = ref.form, input = ref.input, label = ref.label, a = ref.a;

GetSummaryData = require('../functions/get-summary-data.js');

SummaryData = require('./summary-data.js');

Summary = React.createClass({
  getInitialState: function() {
    return {
      data: false
    };
  },
  handleDone: function() {
    return this.props.changeStep(0);
  },
  handleBack: function() {
    return this.props.changeStep(4);
  },
  componentDidMount: function() {
    var _this;
    _this = this;
    return GetSummaryData(this.props.data).then(function(rsp) {
      return _this.setState({
        data: rsp
      }, function() {
        console.log(_this.state.data);
        return _this.forceUpdate();
      });
    });
  },
  render: function() {
    return div({
      className: 'container',
      id: 'summary-container'
    }, div({
      className: 'row'
    }, div({
      className: 'col-sm-2'
    }, a({
      className: 'btn btn-primary',
      onClick: this.handleBack
    }, 'Back')), div({
      className: 'col-sm-8 summary-main-title'
    }, h3({}, "Summary"), p({}, "A summary of your order is below. Once you made sure everything is correct, confirm your order at the bottom.")), div({
      className: 'col-sm-2'
    })), React.createElement(SummaryData, {
      data: this.state.data
    }), a({
      className: 'btn btn-primary',
      onClick: this.handleDone
    }, 'Done'));
  }
});

module.exports = Summary;
